# Request to re-initialize PGO session for a new drone
# drone_id is automatically assigned
string gps_topic                # "" = GNSS disabled for this session
string orientation_topic        # "" = external orientation disabled for this session
---
# Response
bool success
string message
uint8 drone_id                  # Automatically assigned drone ID for the new session
uint32 next_keyframe_index      # The keyframe index where the new session will start
